[package]
name = "crates_io_trustpub"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[lints]
workspace = true

[features]
test-helpers = ["dep:bon", "dep:mockall", "dep:serde_json"]

[dependencies]
anyhow = "=1.0.104"
async-trait = "=0.1.92"
bon = { version = "=3.10.0", optional = true }
chrono = { version = "=0.4.45", features = ["serde"] }
crates_io_version = { path = "../crates_io_version" }
jsonwebtoken = { version = "=11.0.0", features = ["aws_lc_rs"] }
mockall = { version = "=0.15.0", optional = true }
rand = "=0.10.2"
reqwest = { version = "=0.13.4", features = ["gzip", "json"] }
regex = "=1.13.1"
secrecy = "=0.10.3"
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = { version = "=1.0.151", optional = true }
sha2 = "=0.11.0"
thiserror = "=2.0.20"
tokio = { version = "=1.53.1", features = ["sync"] }
tracing = "=0.1.44"

[dev-dependencies]
bon = "=3.10.0"
claims = "=0.8.0"
clap = { version = "=4.6.6", features = ["derive", "env", "unicode", "wrap_help"] }
insta = { version = "=1.48.0", features = ["json", "redactions"] }
mockito = "=1.7.2"
serde_json = "=1.0.151"
tokio = { version = "=1.53.1", features = ["macros", "rt-multi-thread"] }
