backend_lint:
  - .github/workflows/**
  - crates/**
  - src/**
  - Cargo.lock
  - Cargo.toml
  - rust-toolchain.toml

backend_deps:
  - .github/workflows/**
  - Cargo.lock
  - deny.toml
  - rust-toolchain.toml

backend_migrations:
  - .github/workflows/**
  - migrations/**
  - diesel-guard.toml

backend_test:
  - .github/workflows/**
  - crates/**
  - migrations/**
  - src/**
  - Cargo.lock
  - Cargo.toml
  - diesel.toml
  - rust-toolchain.toml

frontend_lint:
  - .github/workflows/**
  - package.json
  - pnpm-lock.yaml
  - '**/*.{css,gjs,hbs,mjs,js,ts}'

  # Include all markdown files for `prettier` checks
  - '**/*.md'

frontend_test:
  - .github/workflows/**
  - app/**
  - packages/crates-io-msw/**
  - public/**
  - tests/**
  - ember-cli-build.js
  - package.json
  - pnpm-lock.yaml
  - testem.js

msw_test:
  - .github/workflows/**
  - packages/crates-io-msw/**
  - pnpm-lock.yaml

e2e_test:
  - .github/workflows/**
  - app/**
  - e2e/**
  - packages/crates-io-msw/**
  - public/**
  - tests/**
  - ember-cli-build.js
  - package.json
  - playwright.config.ts
  - pnpm-lock.yaml

svelte:
  - .github/workflows/**
  - svelte/**
  - pnpm-lock.yaml

zizmor:
  - .github/workflows/**
