packages:
  - 'packages/*'
  - 'svelte/'

shellEmulator: true
ignoreWorkspaceRootCheck: true

peerDependencyRules:
  allowAny:
    - eslint

allowBuilds:
  '@percy/core': true
  esbuild: true
  msw: true
  core-js: false
  sharp: true
  protobufjs: false

patchedDependencies:
  '@pierre/trees@1.0.0-beta.4': patches/@pierre__trees@1.0.0-beta.4.patch
