CREATE TABLE IF NOT EXISTS abandoned_usernames
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR     NOT NULL,
    previous_user_id   INTEGER
        CONSTRAINT fk_abandoned_usernames_previous_user_id
            REFERENCES users
            ON DELETE SET NULL,
    adopted_at   TIMESTAMPTZ,
    abandoned_at TIMESTAMPTZ NOT NULL,
    available_at TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE abandoned_usernames IS
    'Usernames previously associated with users';
COMMENT ON COLUMN abandoned_usernames.id IS
    'Unique identifier of the `abandoned_usernames` row';
COMMENT ON COLUMN abandoned_usernames.username IS
    'The abandoned username in question (use `canon_username()` for normalization, if needed)';
COMMENT ON COLUMN abandoned_usernames.previous_user_id IS
    'The ID of the user who was using this username for this time period, or NULL if the user was deleted';
COMMENT ON COLUMN abandoned_usernames.adopted_at IS
    'Date and time the user began using this username (may be NULL if not available)';
COMMENT ON COLUMN abandoned_usernames.abandoned_at IS
    'Date and time the user stopped using this username (due to name change, account deactivation, or similar)';
COMMENT ON COLUMN abandoned_usernames.available_at IS
    'Date and time this username will be available to other users';

-- safety-assured:start
-- This table doesn't exist yet, so creating this index concurrently isn't necessary.
CREATE INDEX IF NOT EXISTS
    abandoned_usernames_canon_username_index
    ON abandoned_usernames (canon_username(username));
-- safety-assured:end
