- banner:
  - link "crates.io":
    - /url: /
  - search:
    - textbox "Search":
      - /placeholder: Type 'S' or '/' to search
    - button "Search"
  - navigation:
    - 'button "Change color scheme. Current: system"'
    - button "User 1"
- main:
  - heading "foo" [level=1]
  - text: This is the description for the crate called "foo"
  - button "Follow"
  - navigation "foo crate subpages":
    - list:
      - listitem:
        - link "Readme":
          - /url: /crates/foo
      - listitem:
        - link "1 Version":
          - /url: /crates/foo/versions
      - listitem:
        - link "Dependencies":
          - /url: /crates/foo/dependencies
      - listitem:
        - link "Dependents":
          - /url: /crates/foo/reverse_dependencies
      - listitem:
        - link "Security":
          - /url: /crates/foo/security
      - listitem:
        - link "Settings":
          - /url: /crates/foo/settings
  - heading "Owners" [level=2]
  - button "Add Owner"
  - link "User 1 (user-1)":
    - /url: /users/user-1
    - img "User 1 (user-1)"
  - link "User 1":
    - /url: /users/user-1
  - text: user-1@crates.io
  - button "Remove"
  - heading "Trusted Publishing" [level=2]
  - link "Learn more":
    - /url: /docs/trusted-publishing
  - link "Add":
    - /url: /crates/foo/settings/new-trusted-publisher
  - table:
    - rowgroup:
      - row "Publisher Details Actions":
        - columnheader "Publisher"
        - columnheader "Details"
        - columnheader "Actions"
    - rowgroup:
      - 'row /GitHub Repository: rust-lang\/crates\.io · Owner ID: \d+ Workflow: ci\.yml Remove/':
        - cell "GitHub"
        - 'cell /Repository: rust-lang\/crates\.io · Owner ID: \d+ Workflow: ci\.yml/':
          - strong: "Repository:"
          - link "rust-lang/crates.io":
            - /url: https://github.com/rust-lang/crates.io
          - text: ""
          - strong: "Workflow:"
          - link "ci.yml":
            - /url: https://github.com/rust-lang/crates.io/blob/HEAD/.github/workflows/ci.yml
        - cell "Remove":
          - button "Remove"
      - 'row /GitLab Repository: johndoe\/crates\.io · Namespace ID: \d+ Workflow: \.gitlab-ci\.yml Environment: production Remove/':
        - cell "GitLab"
        - 'cell /Repository: johndoe\/crates\.io · Namespace ID: \d+ Workflow: \.gitlab-ci\.yml Environment: production/':
          - strong: "Repository:"
          - link "johndoe/crates.io":
            - /url: https://gitlab.com/johndoe/crates.io
          - text: ""
          - strong: "Workflow:"
          - link ".gitlab-ci.yml":
            - /url: https://gitlab.com/johndoe/crates.io/-/blob/HEAD/.gitlab-ci.yml
          - strong: "Environment:"
          - text: ""
        - cell "Remove":
          - button "Remove"
  - checkbox "Require trusted publishing for all new versions When enabled, new versions can only be published through configured trusted publishers. Publishing with API tokens will be rejected."
  - text: Require trusted publishing for all new versions When enabled, new versions can only be published through configured trusted publishers. Publishing with API tokens will be rejected.
  - heading "Danger Zone" [level=2]
  - link "Delete this crate":
    - /url: /crates/foo/delete
- contentinfo:
  - heading "Rust" [level=2]
  - list:
    - listitem:
      - link "rust-lang.org":
        - /url: https://www.rust-lang.org/
    - listitem:
      - link "Rust Foundation":
        - /url: https://foundation.rust-lang.org/
    - listitem:
      - link "The crates.io team":
        - /url: https://www.rust-lang.org/governance/teams/dev-tools#team-crates-io
  - heading "Get Help" [level=2]
  - list:
    - listitem:
      - link "The Cargo Book":
        - /url: https://doc.rust-lang.org/cargo/
    - listitem:
      - link "Support":
        - /url: /support
    - listitem:
      - link "System Status":
        - /url: https://status.crates.io/
    - listitem:
      - link "Report a bug":
        - /url: https://github.com/rust-lang/crates.io/issues/new/choose
  - heading "Policies" [level=2]
  - list:
    - listitem:
      - link "Usage Policy":
        - /url: /policies
    - listitem:
      - link "Security":
        - /url: /policies/security
    - listitem:
      - link "Privacy Policy":
        - /url: https://foundation.rust-lang.org/policies/privacy-policy/
    - listitem:
      - link "Code of Conduct":
        - /url: https://www.rust-lang.org/policies/code-of-conduct
    - listitem:
      - link "Data Access":
        - /url: /data-access
    - listitem:
      - link "Rate Limits":
        - /url: /docs/rate-limits
  - heading "Social" [level=2]
  - list:
    - listitem:
      - 'link "GitHub: rust-lang/crates.io"':
        - /url: https://github.com/rust-lang/crates.io/
    - listitem:
      - 'link "Zulip: #t-crates-io"':
        - /url: https://rust-lang.zulipchat.com/#streams/318791/t-crates-io
    - listitem:
      - 'link "X: @cratesiostatus"':
        - /url: https://twitter.com/cratesiostatus