//! AUTO-GENERATED by update-data.py - DO NOT EDIT MANUALLY

use ipnetwork::{IpNetwork, Ipv4Network, Ipv6Network};
use std::net::{Ipv4Addr, Ipv6Addr};

/// Fastly IP ranges.
#[rustfmt::skip]
pub const FASTLY_NETWORKS: &[IpNetwork] = &[
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(23, 235, 32, 0), 20).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(43, 249, 72, 0), 22).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(103, 244, 50, 0), 24).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(103, 245, 222, 0), 23).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(103, 245, 224, 0), 24).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(104, 156, 80, 0), 20).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(140, 248, 64, 0), 18).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(140, 248, 128, 0), 17).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(146, 75, 0, 0), 17).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(151, 101, 0, 0), 16).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(157, 52, 64, 0), 18).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(167, 82, 0, 0), 17).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(167, 82, 128, 0), 20).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(167, 82, 160, 0), 20).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(167, 82, 224, 0), 20).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(172, 111, 64, 0), 18).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(185, 31, 16, 0), 22).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(199, 27, 72, 0), 21).unwrap()),
    IpNetwork::V4(Ipv4Network::new_checked(Ipv4Addr::new(199, 232, 0, 0), 16).unwrap()),
    IpNetwork::V6(Ipv6Network::new_checked(Ipv6Addr::new(0x2a04, 0x4e40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0), 32).unwrap()),
    IpNetwork::V6(Ipv6Network::new_checked(Ipv6Addr::new(0x2a04, 0x4e42, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0), 32).unwrap()),
];
